### ISSUE TITLE
Bad Substitution at line 114

### ISSUE THREAD

**Issue by codeplus254** [kolbasa/git-repo-watcher#4]
Fantastic! However, I got errors when pulling changes:
`./git-repo-watcher: line 114: ${commit_message@Q}: bad substitution`

Version of bash:
`GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.`

**Solution**:  Update bash version to at least v4.4 or get rid of the echo line printing the commit message

Keep it up!!!

**Comment by kolbasa** [comment]
Thanks for the hint. I'll take a closer look at it tomorrow. :+1:

**Comment by kolbasa** [comment]
I fixed it. The script now supports bash with version `3.0`-`5.0`.
Thank you :+1:
