### ISSUE TITLE
does it support windows?

### ISSUE THREAD

**Issue by Mello21century** [kolbasa/git-repo-watcher#5]
I can see the directory path is prefixed by "/" by default
If we can get the environment os and prepend if in Linux or Mac would be supported?

**Comment by kolbasa** [comment]
I don't know. But now that you ask, I'll give it a try and report later.

**Comment by kolbasa** [comment]
I am not a Windows person, but I have now tried the Linux subsystem.
It works 100%. I installed Ubuntu 18.04 LTS and 20.04 LTS from the Windows App Store.

* In [**Ubuntu 18.04 LTS**](https://www.microsoft.com/en-us/p/ubuntu-1804-lts/9n9tngvndl3q?activetab=pivot:overviewtab) it works directly without any dependencies.
* In [**Ubuntu 20.04 LTS**](https://www.microsoft.com/en-us/p/ubuntu-2004-lts/9n6svws3rx71?activetab=pivot:overviewtab) there is a [reported bug](https://github.com/microsoft/WSL/issues/4898) that was introduced by Microsoft.

For a temporary fix you can run the following commands on Ubuntu 20.04 LTS:
```bash
sudo apt update
wget https://launchpad.net/~rafaeldtinoco/+archive/ubuntu/lp1871129/+files/libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb
sudo dpkg --install libc6_2.31-0ubuntu8+lp1871129~1_amd64.deb
sudo apt-mark hold libc6
sudo apt --fix-broken install
sudo apt full-upgrade
```
After that, it works without problems.

But what's even more interesting is that it runs directly in the [**Git Shell**](https://git-scm.com/downloads). 
So you don't even need a Linux subsystem. Git already installs a minimal version of Bash on Windows computers.

The only thing to watch out for is the file paths.

For Ubuntu it looks like this:
```
./git-repo-watcher -d "/mnt/c/Users/Michael/Downloads/your-git-repository"
```

For Git Shell it looks like this:
```
./git-repo-watcher -d "/C/Users/Michael/Downloads/your-git-repository"
```

Note the file path separators. The Linux type is still used (`/` not `\`).
Depending on the hard disk designation, the `/C/` should be replaced.

I'll leave this open until I update the README-file.
If you have problems, just write.

**Comment by kolbasa** [comment]
I updated the documentation. Thank you and greetings from Germany.
