### ISSUE TITLE
push to another repo

### ISSUE THREAD

**Issue by sicenul** [kolbasa/git-repo-watcher#6]
Well I know if I request this, it;s not match with the name of this script 😃 
But, please consider to add a function to push to another repo.
The purpose is I wanted to create a backup repo, so everytime there's a change on a repo, after a pull, it will push to another repo.
Thanks.

Edit: Hmm looks like it can be done using hooks 😄  but how to do:
git pull origin master, then:
git push backup master

**Comment by kolbasa** [comment]
Yes, that would be the responsibility of the hooks file.
Basically, you just have to copy the folder content to your second repository and then commit

It sounds like you want to back up the repository every time a commit is pushed?
I think there are much better tools for such cases.

I can write you the hook-method if you still need it.

**Comment by sicenul** [comment]
Thank you, I really appreciate if you can help me with hook-method.
And yes, I want to backup the repository. After a commit is pushed, git-repo-watcher will update local repository, then it will push to another repository.

origin = http://repo.localhost/app.git
backup = http://backup.localhost/app.git

If I did it manually then:
git pull origin master
git push backup master

**Comment by kolbasa** [comment]
Ok, I understand now. You are working with two remotes.

You have to set the upstream to origin first.
```
git branch -u origin/master
```

Change the `change_pulled` hook-method to:
```bash
change_pulled() {
    echo "Syncing the remotes: $*"
    git push --mirror backup
}
```

Then start the watcher-script.

This will mirror your repository.
You may have to write one or two lines for password caching.

I tested it. It works perfectly.
And is at second glance a good idea. I'm gonna put that in the `README.md`. :+1:

**Comment by sicenul** [comment]
Great :+1: 
Again, thanks a bunch. Can't wait to test it.
Closing this issue for now.
