### ISSUE TITLE
Disable endless loop check

### ISSUE THREAD

**Issue by IVIJL** [kolbasa/git-repo-watcher#7]
Hey, added some IF statements to add feature if I do "-i 0" it will run just once. Which is great for run it through cron once in a while and not "endlessly".
Would be cool if it had from start, otherwise it's perfect, THANKS

**Comment by stoutgz** [comment]
@IVIJL could you share your changes in a fork?

**Comment by kolbasa** [comment]
I have only now seen the request.
I will add the option to the script in the next few days.

**Comment by stoutgz** [comment]
Cool! thanks @kolbasa!

**Comment by kolbasa** [comment]
The change is online now. I introduced a new option `-o`.
```bash
./git-repo-watcher -d "/path/to/your/repository" -o
```
